import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { createClient } from 'contentful'
/* components */
import RecipeCard from '../components/RecipeCard'
/* types */
import { Post } from '../Type'

// 仕上げにvercelのhookをcontentfulに登録することを忘れずに！

type Props = {
  posts: Post[]
}

export const Home = ({ posts }: Props) => {
  return (
    <div>
      <Head>
        <title>Haruka blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-red-500">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className="recipe-list">
          {posts.map((post) => {
            return <RecipeCard key={post.sys.id} recipe={post} />
          })}
        </div>
      </main>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  })

  const res = await client.getEntries({ content_type: 'post' })

  return {
    props: {
      posts: res.items,
    },
    revalidate: 10,
  }
}
